services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kozker_backend
    expose:
      - "8000"
    environment:
      - SUPABASE_URL
      - SUPABASE_KEY
      - BACKEND_BASE_URL
      - USE_N8N
      - N8N_GENERATE_JOBS_URL
      - N8N_EXTRACT_SKILLS_URL
      - N8N_MATCH_CANDIDATES_URL
      - N8N_GENERATE_QUESTIONS_URL
      - N8N_REGENERATE_JOBS_URL
      - N8N_REFINE_QUESTION_URL
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL:-https://covhcpsyliesrgkjxhai.supabase.co}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY:-sb_publishable_V69YOpwZKjrT1BT8k609nQ_MBzXV80b}
        NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: ${NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY:-sb_publishable_V69YOpwZKjrT1BT8k609nQ_MBzXV80b}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-}
    container_name: kozker_frontend
    expose:
      - "3000"
    environment:
      - NEXT_PUBLIC_SUPABASE_URL
      - NEXT_PUBLIC_SUPABASE_ANON_KEY
      - NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
      - NEXT_PUBLIC_API_URL
    restart: always
    depends_on:
      - backend
